### ISSUE TITLE
Auctionator causes a popup saying that it has been blocked by the Blizzard UI.

### ISSUE THREAD

**Issue by Gutitout** [Auctionator/Auctionator#1109]
2x [ADDON_ACTION_FORBIDDEN] AddOn "Auctionator" tried to call the protected function "GuildControlSetRank()".
<string>:"@!BugGrabber\BugGrabber.lua":587: in function <!BugGrabber\BugGrabber.lua:587>
<string>:"=[C]"]: in function "GuildControlSetRank"
[string "@Interface_TBC\FrameXML\FriendsFrame.lua":2510: in function "GuildControlPopupFrame_Initialize"
<string>:"@Interface_TBC\FrameXML\FriendsFrame.lua":973: in function "FriendsFrame_OnEvent"
<string>:"*:OnEvent":1: in function <string>:"*:OnEvent":1
<string>:"=[C]"]: in function "SortGuildRoster"
[string "*:OnClick":2: in function <string>:"*:OnClick":1

**Comment by Gutitout** [comment]
Auctionator-9.1.12-bcc.zip

**Comment by plusmouse** [comment]
Did you do anything specific to trigger this error?

**Comment by Gutitout** [comment]
This would sometimes pop up when I opened the Friends and Guild members tab. To continue I have been /reload, and then it does not pop up for awhile. It's hard for me to reproduce, so you could do the same.

**Comment by Gutitout** [comment]
I would have sent this to you a long time ago, but I just now downloaded an old version of !BugGrabber that seems to work with Classic TBC. The version of !BugGrabber that CurseForge delivers does not work in Classic TBC.

**Comment by Gutitout** [comment]
This time I just Set Focus on a mob.
2x [ADDON_ACTION_FORBIDDEN] AddOn "Auctionator" tried to call the protected function "FocusUnit()".
<string>:"@!BugGrabber\BugGrabber.lua":587: in function <!BugGrabber\BugGrabber.lua:587>
<string>:"=[C]"]: in function "FocusUnit"
[string "@Interface_TBC\FrameXML\UnitPopup.lua":1954: in function "func"
<string>:"@FrameXML\UIDropDownMenu.lua":960: in function "UIDropDownMenuButton_OnClick"
<string>:"*:OnClick":1: in function <string>:"*:OnClick":1

**Comment by plusmouse** [comment]
Try reinstalling Auctionator, as your install might be corrupted (its supposed to include code that prevents the above errors from happening). Otherwise, try the below:

Could you please run this command in-game directly after loading your character:
```
/console taintLog 1
```
And then play until you get the error again? Once you do, please log out (this is crucial, the WoW client uses a buffer for writing to the log and it can take up to 10 minutes for errors to appear) and upload the contents of `World of Warcraft\_retail_\Logs\taint.log` to https://pastebin.com/ and paste the link here.

This will help me figure out what is causing the error.

**Comment by plusmouse** [comment]
Recently merged #1135 which should resolve this. Thanks for the report.
