### ISSUE TITLE
Improvement request: canceling undercut items via keybind faster

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#1124]
**Is your feature request related to a problem? Please describe.**
When using a set keybind to quickly cancel undercut items (in Cancelling tab) you will notice that spamming the key quickly does nothing as the UI is waiting for 1st item to cancel before registering any clicks to cancel 2nd item.
Now if you simply click on each item with your mouse, you can "queue" up as many items as you want, and they will all cancel one by one in a queue.

**Describe the solution you'd like**
If possible, make keybind work in same style as the mouse. 1 press of a button = cancel 1st item, next press of a button puts 2nd item in cancel queue, and so on.

I hope this is something you'd be interested in, as where I am the latency is quite high, so each time I use the button to cancel items, i smash it like 5-10 times before the item is actually cancelled. 
Thanks

**Comment by plusmouse** [comment]
This is a hard item for me to test, as I can't easily get the queuing functionality for me to test with as my connection is too fast, and the "Cancel Undercut" button only disables when I'm clicking too quickly.

The restrictions on clicking the "Cancel Undercut" button (and consequently the key binding) were added because of users clicking the button too fast, causing it to queue up cancellations with some of them failing, and then skipping the failed ones. Adding in more code to compensate and detect the auctions that failed to cancel was deemed unnecessary at the time because the throttling delay on the button appeared minimal, and was a much simpler change.

However you can try removing the throttling restrictions on the button by making this change: Replace line 231 `self.CancelNextButton:Disable()` of `Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua` with `self:SetCancel()`
```diff
diff --git a/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua b/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua
index 7e77cb0..749b791 100644
--- a/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua
+++ b/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua
@@ -228,5 +228,5 @@ function AuctionatorUndercutScanMixin:CancelNextAuction()
     self.undercutAuctions[1].auctionID
   )

-  self.CancelNextButton:Disable()
+  self:SetCancel()
 end
```
Similarly there's a restriction on the "Post" button in the "Selling" tab which you may have noticed.

Let me know if that helps/resolves your issue.

**Comment by plusmouse** [comment]
This didn't appear to resolve the issue. Guessing when a cancel request will be accepted is tricky, so leaving it using the build-in throttling is the best option.
