### ISSUE TITLE
Why is there no "Cloak" "Jewelry" option

### ISSUE THREAD

**Issue by qih5544** [Auctionator/Auctionator#1140]
I can't find the "Cloak" "Jewelry" options

**Comment by plusmouse** [comment]
Are you referring to these search options?
![image](https://user-images.githubusercontent.com/60280559/160592511-be81a076-e03b-4833-8e23-569fbfeb0ad4.png)

It is missing Cloak and Jewlery options, which since #1137 was reported I've been looking at fixing.

**Comment by plusmouse** [comment]
This has now been fixed in the latest alpha. Available from Curseforge in a few minutes.
![image](https://user-images.githubusercontent.com/60280559/161385278-989ab083-c0ff-4959-ad6b-26c5316d163a.png)

Or here: 
[TBC](https://github.com/Auctionator/Auctionator/files/8402587/Auctionator-9.2.11-3-g9f0444d-bcc.zip)
[SoM](https://github.com/Auctionator/Auctionator/files/8402588/Auctionator-9.2.11-3-g9f0444d-classic.zip)
