### ISSUE TITLE
"Refresh all pages when clicking the Refresh button" option doesn't stay turned off

### ISSUE THREAD

**Issue by Kolmarwow** [Auctionator/Auctionator#1152]
## Brief Description of Bug

The "Refresh all pages when clicking the Refresh button" option will automatically turn itself back on as soon as you open the interface options again. 

## Steps to Reproduce

Interface -> Addons -> Auctionator -> Shopping -> Turn off "Refresh all pages when clicking the Refresh button" -> Go to another tab and then go back to "Shopping" and you'll see the option has turned itself back on again.

## Loaded Addons

Tested with all addons off and with a fresh WTF folder so this doesn't seem to be a compatibility issue. 

## Back Trace (LUA Error Output)

No LUA errors present according to Bugsack.

**Comment by plusmouse** [comment]
Confirmed, it is a bug. Fixed in the latest alpha, available from Curseforge shortly, or from here
[SoM](https://github.com/Auctionator/Auctionator/files/8598885/Auctionator-9.2.14-2-g4e475ae-classic.zip)
[TBC](https://github.com/Auctionator/Auctionator/files/8598886/Auctionator-9.2.14-2-g4e475ae-bcc.zip)
