### ISSUE TITLE
Auctionator not working?

### ISSUE THREAD

**Issue by Eithical** [Auctionator/Auctionator#1161]
Hey so I've been trying to use this addon but for some reason when I install it and try to use it, it just doesn't show up. I Have it downloaded and installed and I have it checked off in the addon tab (ingame) but still nothing happens. When I look at the interface tab ingame nothing shows up when I click on Auctionator, its just blank. Plz help 

I've also tried and delete all my other addons and it still doesn't work.

**Comment by Eithical** [comment]
Sorry forgot to mention that this is on classic and not retail.

**Comment by plusmouse** [comment]
Have you tried downloading Auctionator again? Downloading the retail instead of the classic version would cause this issue.

When it is installed with the right version, the "Shopping", "Selling", "Cancelling" and "Auctionator" tabs will appear in the AH
![image](https://user-images.githubusercontent.com/60280559/169667834-7c50db52-0678-4813-9e70-247ed6bbbfb0.png)

**Comment by plusmouse** [comment]
If that still doesn't work can you install BugGrabber and BugSack and report whatever errors they record.

**Comment by Eithical** [comment]
Oh wow that worked! Yeah I must've been installing retail version. Hell yeah man thank you!
