### ISSUE TITLE
Add "skip" button on the vendor price warning popup

### ISSUE THREAD

**Issue by SiJiL82** [Auctionator/Auctionator#1266]
The "You can make more money selling this to a vendor" popup window feature is fantastic - something I think could make it a bit smoother is if there was a "skip" button aswell, instead of having to click cancel, then also click skip in the main window.

**Comment by Arkios64** [comment]
Definitely supporting this.

Also, the explanation for this option should probably be changed, currently it sounds like this function is Vanilla and turned OFF with the checkmark:
![image](https://user-images.githubusercontent.com/78656397/203683944-a97c284c-5ac0-4b26-aa53-25d74227f0d4.png)
So, instead of **"Lets you remove** the confirmation" it should be **"Adds a** confirmation". Just noticed that I actually turned it off for that exact reason when checking if `deposit + vendor price` determines if the message pops up, which it does.

**Comment by Rezy942** [comment]
+1 to skip a warning popup

**Comment by plusmouse** [comment]
Find this in the latest alphas (available shortly)
![image](https://github.com/Auctionator/Auctionator/assets/60280559/99d99573-359a-41d1-9321-ac385d23dc08)
