### ISSUE TITLE
Undercut scan interrputs sometimes

### ISSUE THREAD

**Issue by Ma55L89** [Auctionator/Auctionator#1269]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

See title. The undercut scan interrupts sometimes. Mostly after scanning the AH and the client running a period of time. I note also a short "hickup" or micro stutter for a frame at that moment when this is happening.

## Steps to Reproduce

I opend the AH interface, do a normal scan (automatic after open the AH) and then do an undercut scan. It interrupts at the middle of the scan and freezes while the "scan"-button was disabled. So i could not do a rescan, had to leave the NPC and open the interface for a second time to do it again.
It happens not always... so to reproduce: Try to play a bit / run the client for some while, do a scan and have a large list of auctions ( > 20 in my case).

## Loaded Addons

Auctionator
Decursive
Details!
ErrorFilter
GroupfinderFlags
HandyNotes
Ludwig
MapCoords
Method Raid Tools
Pawn
PetTracker
Simulationcraft
Threat Plates
WeakAuras
Deadly Boss Mods

I will post a screenshot if it happens again.
Thanks so far for this awesome addon :)

**Comment by Ma55L89** [comment]
![WoWScrnShot_111222_073350](https://user-images.githubusercontent.com/118039430/201461031-e0b8d82c-e2ea-4b2c-9129-a7ea0d31d7f2.jpg)

**Comment by Araldwenn** [comment]
I'm having the exact same issue, except it happens all the time and I need to run Auctionator multiple times so it scans for undercut.
I've tried with only auctionator installed, and same.
I've notived someting that may be related. I've later installed Collectionator and Journalator, and when I press the scan button, it stucks at 10%. I have to wait 15mn so I can scan again.
Just as if something was keeping scans to continue.

Buggrabber shows no error.

**Comment by plusmouse** [comment]
# Undercut scan
I think this is an issue I've hit (and fixed) with the Collectionator "Start Purchasing" buttons - that had the problem with scans unexpectedly stopping, and the solution was to add a few checks for when the scan stops when it should so the addon retries automatically.

Is this on a specific realm (so I can replicate it for testing a fix)?

# Collectionator scan
This is a Blizzard problem, as Collectionator/Auctionator send the scan request to the server, can't just retry because that particular scan is limited to once every 15 minutes, even if it fails.

**Comment by Araldwenn** [comment]
I'm on Medivh, and I've got a few characters on Elune too, but havn't tried there.

**Comment by plusmouse** [comment]
@Araldwenn Got a version of Auctionator that should fix the issue. Could you try it and report back?

[Auctionator-10.0.13-2-g1e654e4.zip](https://github.com/Auctionator/Auctionator/files/10050651/Auctionator-10.0.13-2-g1e654e4.zip)

**Comment by Araldwenn** [comment]
I gave a try to this update, seem to be fine, but at least I tried Something, cause the last time I posted auctions , I removed 1 object that seemed to be causing issues with cancelling auctions. So I posted it again, I now have to wait to be undercut and try and see if this item was really causing issues. Envoyé à partir de Courrier pour Windows De : plusmouseEnvoyé le :dimanche 20 novembre 2022 21:43À : Auctionator/AuctionatorCc : Araldwenn; MentionObjet :Re: [Auctionator/Auctionator] Undercut scan interrputs sometimes (Issue ***@***.*** Got a version of Auctionator that should fix the issue. Could you try it and report back?Auctionator-10.0.13-2-g1e654e4.zip—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by plusmouse** [comment]
I've put the fix in the newest alpha (available from Curseforge shortly)
[Auctionator-10.0.13-2-g5674dcf.zip](https://github.com/Auctionator/Auctionator/files/10056810/Auctionator-10.0.13-2-g5674dcf.zip)
