### ISSUE TITLE
AddOn 'Auctionator' tried to call the protected function 'PickupContainerItem()'

### ISSUE THREAD

**Issue by kev22257** [Auctionator/Auctionator#1282]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Tried to use my Hearthstone

## Back Trace (LUA Error Output)

1x [ADDON_ACTION_BLOCKED] AddOn 'Auctionator' tried to call the protected function 'PickupContainerItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `PickupContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1341: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

Locals:
Skipped (In Encounter)

**Comment by plusmouse** [comment]
What have you done before this error triggered? Specifically anything that may have triggered Auctionator code.

**Comment by kev22257** [comment]
That’s the weird part, I don’t see any pattern. It seems to be triggered randomly when I interact with something in my bag. I’m not running any bag, add-ons or anything.

**Comment by plusmouse** [comment]
Did you use the Auction House on the session/reload that the error happened in?

**Comment by plusmouse** [comment]
Also, could you provide a list of your addons so I can test against them too?

**Comment by kev22257** [comment]
I don’t think I had previously used the auction house in the same load, but I will monitor that going forward because it happens semi-often. I will get the add-on list for you tomorrow when I’m back online. Thank you for the quick responses!

**Comment by kev22257** [comment]
Okay, here is my list:

AstralKeys 3.64
Auctionator 10.0.16
BlizzMove 3.5.6
BlizzGrabber 10.0.1
ChatCopyPaste 1.15
CopyPasta 1.12
DBM 210475f
Details #Details.DF.Wrath.10259.146
MountJournalEnhanced 2.20.3
Raider.IO 10.0.0
SoulshapeJournal 1.2.2
TomTom 3.3.5-release
WeakAuras 5.2.1

**Comment by plusmouse** [comment]
I've installed and enabled those add-ons (minus BlizzGrabber that I couldn't find) - hopefully I hit the error at some point, as testing so far hasn't replicated it

**Comment by Mykoice** [comment]
Hey, in case you didn't find the cause, on-use items from Dragonflight seem to be an issue. Specifically, items that give you knowledge points for professions, though some other on-use items also seem to trigger it. 

Here's the error from BugGrabber.
> 5x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'UNKNOWN()'.
> [string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `UseContainerItem'
> [string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
> [string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
> [string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

**Comment by plusmouse** [comment]
@Mykoice Can you run `/console taintLog 1` and then play, when you get an error can you close the WoW client and upload  the `[wow directory]/_retail_/Logs/taint.log` file here? It should help me figure out what broke.

**Comment by Mykoice** [comment]
Sorry for late reply; enjoying the dragon-flying mechanics.

I got a couple of items that are all giving me the error, and here's the code from the logs.

> 11/30 21:58:21.121  Interface/FrameXML/ContainerFrame.lua:1589 GetBagID()
> 11/30 21:58:21.121  An action was blocked because of taint from Auctionator - 
> 11/30 21:58:21.121      UseContainerItem()
> 11/30 21:58:21.121      Interface/FrameXML/ContainerFrame.lua:1409
> 11/30 21:58:21.121      ContainerFrameItemButton_OnClick()
> 11/30 21:58:21.121      Interface/FrameXML/ContainerFrame.lua:1461

It does this on repeat. Based on this, I think it's related to the new regent bag slot they added. There's the default bag, four extra bags since vanilla, but they added in a new regent-only bag slot. Not 100% if it was added in the pre-patch or when the game launched. 

If that isn't the case, here are two of the items that cause the error. 

https://i.imgur.com/XU3T5PK.png
https://i.imgur.com/hu2Cnr7.png

And here are all the bags now. 

https://i.imgur.com/pcBQF2i.png

**Comment by kev22257** [comment]
I will also do some experimenting, but I found that the old WoD items (like your Garrison hearthstone) would also trigger it.

**Comment by Mykoice** [comment]
Update: Removing the bag out of the regent-bag slot has made everything work.

**Comment by plusmouse** [comment]
I've opened up a character with a Garrison hearthstone and it doesn't error. What did you do in the session (after last login/reload) prior to the error happening?

**Comment by Mykoice** [comment]
I was trying to recreate the issue; but everything I was doing didn't seem to trigger it. I'll keep trying tomorrow.

**Comment by Mykoice** [comment]
Okay, so. I managed to get the error again, but I'm not sure which one was/is the cause. I had taint enabled for the entire duration, but after opening the log, there was only the same single error. But what I did end up doing were these things, in roughly this order.

1) Side Quests
2) Unlocked higher renown level with one of the factions (Valdrakken I think?)
3) World-Quests (Races, specifically)
3.5) I did a dungeon in-between where I entered in with ST talent build, changed to MT talents inside, then finished the dungeon + left in the MT talent build. There was also a chest that got looted. Also, I did have to do a /reload because an add-on was causing keybinding issues, but that was at the start of the dungeon. I did change to MT after the reload.
4) Finished two more world-quests.
5) Went to check on the auction house to put stuff up, went to mailbox, went back to AH to re-list expired stuff through Auctioneer, then checked through all the crafting orders to see if there were any. 
6) Finished up another weekly(?) quest, got a loot chest + rep with all renown factions.

Now, up until that point, I'm pretty sure that everything still worked. But between that quest turn-in and me finally getting the error to pop up, I looted from an Expedition Scout's Pack, bags were closed, turned in two quests, first one being a simple conversation while the other gave me a on-use item, then I opened my bags and the error popped up after I tried using the on-use item. The on-use item isn't from Dragonflight, btw. It's a pet rarity level-up. 

I hope this info helps, because I'm clueless.

**Comment by plusmouse** [comment]
I disenchanted several items and got the protected error. I think its because Auctionator was hiding the Blizzard vendor prices
```
12/2 09:26:02.279  Execution tainted by Auctionator while reading ShoppingTooltip1MoneyFrame1 - Interface/FrameXML/GameTooltip.lua:380 GameTooltip_ClearMoney()
12/2 09:26:02.279      ShoppingTooltip1:ameTooltip.xml:146_OnTooltipCleared()
12/2 09:26:02.279      ShoppingTooltip1:Hide()
12/2 09:26:02.279      Interface/SharedXML/Tooltip/TooltipComparisonManager.lua:39 Clear()
12/2 09:26:02.279      Interface/FrameXML/GameTooltip.lua:454
12/2 09:26:02.279      GameTooltip:Hide()
12/2 09:26:02.279      Interface/FrameXML/GameTooltip.lua:643 GameTooltip_Hide()
12/2 09:26:02.279      Interface/FrameXML/ContainerFrame.lua:1479
12/2 09:26:02.279  Interface/FrameXML/ContainerFrame.lua:1589 GetBagID()
12/2 09:26:02.279  An action was blocked because of taint from Auctionator - 
12/2 09:26:02.279      UseContainerItem()
12/2 09:26:02.279      Interface/FrameXML/ContainerFrame.lua:1325
12/2 09:26:02.279      ContainerFrameItemButton_OnClick()
12/2 09:26:02.279      Interface/FrameXML/ContainerFrame.lua:1461
```

**Comment by plusmouse** [comment]
The latest alpha for Auctionator should resolve this issue:
[Auctionator-10.0.16-3-g2c0449e.zip](https://github.com/Auctionator/Auctionator/files/10139968/Auctionator-10.0.16-3-g2c0449e.zip)

If it doesn't I'll reopen the issue.
