### ISSUE TITLE
LUA error while full scan

### ISSUE THREAD

**Issue by Chouu** [Auctionator/Auctionator#133]
Message: ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:733: attempt to index local 'color' (a nil value)
Time: 07/23/16 18:06:27
Count: 6
Stack: ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:733: in function `AuctionFrameBrowse_Update'
...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:260: in function <...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:258>

Locals: numBatchAuctions = 108983
totalAuctions = 108983
button = BrowseButton8 {
 0 = <userdata>
}
buttonName = "BrowseButton8"
buttonHighlight = BrowseButton8Highlight {
 0 = <userdata>
}
iconTexture = BrowseButton7ItemIconTexture {
 0 = <userdata>
}
itemName = BrowseButton8Name {
 0 = <userdata>
}
color = nil
itemCount = BrowseButton7ItemCount {
 0 = <userdata>
}
moneyFrame = BrowseButton7MoneyFrame {
 0 = <userdata>
 vadjust = 0
 trialErrorButton = BrowseButton7MoneyFrameTrialErrorButton {
 }
 moneyType = "AUCTION"
 info = <table> {
 }
 small = 1
 staticMoney = 3135
 maxDisplayWidth = 146
}
yourBidText = BrowseButton7YourBidText {
 0 = <userdata>
}
buyoutFrame = BrowseButton7BuyoutFrame {
 0 = <userdata>
}
buyoutMoney = BrowseButton7BuyoutFrameMoney {
 0 = <userdata>
 vadjust = 0
 trialErrorButton = BrowseButton7BuyoutFrameMoneyTrialErrorButton {
 }
 moneyType = "AUCTION"
 info = <table> {
 }
 small = 1
 staticMoney = 3300
 maxDisplayWidth = 146
}
offset = 0
index = 8
isLastSlotEmpty = true
name = ""
texture = nil
count = 3
quality = -1
canUse = false
level = 1108750640
levelColHeader = nil
minBid = 22800
minIncrement = 0
buyoutPrice = 24000
duration = 3
bidAmount = 0
highBidder = false
bidderFullName = nil
owner = nil
ownerFullName = nil
saleStatus = 0
itemId = 5784
hasAllInfo = false
displayedPrice = 3135
requiredBid = 3135
(for index) = 8
(for limit) = 8
(for step) = 1
i = 8
(*temporary) = <function> defined =[C]:-1
(*temporary) = BrowseButton8Name {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = false
(*temporary) = 1108750640
(*temporary) = nil
(*temporary) = 22800
(*temporary) = 0
(*temporary) = 24000
(*temporary) = 0
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = 5784
(*temporary) = false
(*temporary) = "attempt to index local 'color' (a nil value)"

**Comment by ceylina** [comment]
This is known issue

**Comment by AlexejK** [comment]
Could you please elaborate on "Known Issue"?
Is this something that is caused by WoW client itself and therefore won't be fixed until Blizzard decides to do it or something know to be an issue with Auctionator? In that case - I couldn't find an issue to track this.

I never had this problem prior to 7.0.3 patch - so not sure what the "Know issue" relates to in this case.

**Comment by FireEmerald** [comment]
Got the same error 1000+ times while performing a single full scan. I agree with AlexejK - any further informations about this 'known issue' would be great? @ceylina

**Comment by ceylina** [comment]
"Is this something that is caused by WoW client itself and therefore won't be fixed until Blizzard decides to do it"

Partially. It is a flaw in the Blizzard built in addon for the AuctionUI and how it connects to their back-end functions for reading the databases that contain auction data (server side stuff).. It is caused regardless of addons loaded (including Auctionator) and does not happen on the current Legion Beta servers. It leads us to believe they either have fixed it on their side or it is something not enabled yet in the pre patch that is causing this error. Either way, it is not a game breaking or auctionator breaking error and can be safely ignored.
