### ISSUE TITLE
Filter out unusable items

### ISSUE THREAD

**Issue by SWEPatA** [Auctionator/Auctionator#140]
As title says, adding an option in advanced search for usable items. Like how it is in the default blizzard UI.

**Comment by ceylina** [comment]
I will bring this up and see if we are able to and can easily implement such an option. It traditionally has not been something that was offered but we will look into it.

**Comment by jrob8577** [comment]
I think it's just one of the parameters to `QueryAuctionItems`, so it's probably doable.  Will need to investigate.

**Comment by Jokosin** [comment]
I'd like to add on to this if its ok, this request might fulfill something I'd love to see as well.

When you use the default blizz auction search pane with "Usable Items" checked for things like ore, blizz gives one huge results page instead of 20 or 50 pages. Is it possible to use this method as an option when searching with the Buy tab to (almost 20x) more quickly search for simple stuff?

IE: Search for Leystone Ore, with usable unclicked. I get many pages, with the bottom saying Showing 1-50 of 1350.  But if I click "Usable Items". I get one page, with bottom saying showing 1-1350 of 1350 total.
