### ISSUE TITLE
Cancelation slow

### ISSUE THREAD

**Issue by Araldwenn** [Auctionator/Auctionator#1416]
I have a lot of items at the AH, and after I run a cancelation scan, after maybe 25 cancelation running smoothly, the next ones take about 5 seconds each to cancel (the cancel auction button is grayed for 5 seconds before I can use it again). Closing and reopening auctionator fixes the problem for 2 or 3 more items, but then it gets slow again.
There's no error showing in BugSack.

Other addons running :

Elvui
Chocolate bar
Journalator
Simple addon manager
Ark Inventory
Collectionator
Accountant
Addonskins
AltVault
Elvui Windtools
Expansion Reagents
Item upgrade quality
Mailcommander
Oribos exchange
Postal
Scrap

**Comment by plusmouse** [comment]
This is due to Blizzard throttling addon actions on the AH. There's a point at which Blizzard limits how many requests it will process, and the visible effect of this is cancelling being restricted.

The Cancel Auction button uses the Blizzard APIs to determine when the Blizzard servers will accept a cancellation request, and if it wouldn't accept the request, greys out the button.
