### ISSUE TITLE
disable favorite toggle by simply clicking on item

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1418]
**Is your feature request related to a problem? Please describe.**
Since version 10.1.14-4-gde04fd1, I keep accidentally marking items as favorites by simply clicking on them in the Selling tab.
This wasn't a problem in any previous versions, so now I have rolled back to 10.1.14-1-ge772b68.

**Describe the solution you'd like**
I would like to be able to click on items anywhere to sell without marking them. A simple option to disable this feature to restore previous behavior would be perfect.

**Describe alternatives you've considered**
Maybe make this behavior only work with a modifier key.

**Additional context**
Because of the layout of the Selling window, moving the pointer between the items and the Post button makes it so that it very often lands on the topright corner of the item icons because it is the closest point, so it is very annoying having to pay attention to move it further to not accidentally put marks on items.

**Comment by plusmouse** [comment]
I've removed the change from the latest alphas.
[Auctionator-10.1.14-5-g42ca3c9.zip](https://github.com/Auctionator/Auctionator/files/12206973/Auctionator-10.1.14-5-g42ca3c9.zip)

**Comment by tflo** [comment]
I had the same issues, so thanks for removing.

But basically this feature isn't that bad, it just needs some tuning. As the OP says, a config setting for it would be the first step, and optionally adding a IsModifierKeyDown would be great too!

Last but not least perhaps reducing the clickable area size? I noticed that it has become better after I had increased my icon size from 32 to 40, since the clickable area didn't seem to scale with the icon size.

But probably the better alternative would be to remove the dedicated click area completely, and make it dependent on a specific modifier when the icon is clicked _anywhere_. (AFAICT Alt and Ctrl are unused in the context, so these could be candidates.)
