### ISSUE TITLE
Items hidden from the Selling tab are un-hidden every time the addon updates

### ISSUE THREAD

**Issue by MatthewRyanRead** [Auctionator/Auctionator#1445]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

The Hide list seems to get reset when the addon updates.  It is otherwise remembered across logouts and characters, as expected.

## Steps to Reproduce

1. Right click an item in the Selling tab and click Hide
2. Log out or quit, log back in, verify item is still hidden
3. Quit and update the addon
4. Log back in and see that the item is no longer hidden

## Loaded Addons

ElvUI

## Back Trace (LUA Error Output)

N/A

---

Apologies if this is an addon setting that I've missed, I couldn't find one.

**Comment by plusmouse** [comment]
This is an unfortunate consequence of some bugfixing for items showing the wrong item level or not stacking correctly. The issue has been resolved so that the old hidden items should be now hidden. This latest alpha should resolve the issue:
[Auctionator-10.1.28-1-g421b0ec.zip](https://github.com/Auctionator/Auctionator/files/12907406/Auctionator-10.1.28-1-g421b0ec.zip)

**Comment by MatthewRyanRead** [comment]
Great, looking forward to that release.  Thanks!
