### ISSUE TITLE
Mailbox tooltip bug

### ISSUE THREAD

**Issue by jrob8577** [Auctionator/Auctionator#150]
## Brief Description of Bug

Thank you for this addon, I love the shopping list feature and how Buying works in particular.
I must say I am not very happy with the tooltip changes made in one of the recent updates. They now interfere with the mailmod Postal when you mouseover mails, like this:
https://gyazo.com/30d81b17dd8e36a0e86ebb96c7cd71e8

Even if I disable all the available options in the Tooltips settings, it still looks like:
https://gyazo.com/17c537ad43fead8bcec9d08b2f7acf34
 
If there is a way to fix this? And if not, would it be possible to make a setting to disable Auctionator tooltips completely?

## Loaded Addons

* Postal

From [curse comment](https://mods.curse.com/addons/wow/auctionator?comment=6112).  Possibly related to or duplicates #144

**Comment by ceylina** [comment]
4.0.7 fix from issue #144 fixes this

This is whit tooltips enabled. Not the example showing 

[Hunters Ink]x5
[Midnight Ink]x2
[Cerulean Pigment]x200

Those are from postal

![wowscrnshot_072816_102426](https://cloud.githubusercontent.com/assets/9342192/17218493/9aa67370-54ad-11e6-891d-7386288afb28.jpg)

This is how the fix for 4.0.7 shows when all tooltip settings for Auctionator are disabled

![wowscrnshot_072816_102438](https://cloud.githubusercontent.com/assets/9342192/17218586/e68d8d0a-54ad-11e6-90bd-1a03685c1a74.jpg)

As you can see, those tooltip results are now hidden and only the postal tooltip results are show.

**Comment by jrob8577** [comment]
Fixed in 4.0.7, releasing now.
