### ISSUE TITLE
[Cata classic] All data has been reset after yesterday's update

### ISSUE THREAD

**Issue by prokn4h** [Auctionator/Auctionator#1512]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

All the data and settings has been reset after updating version yesterday.
Settings and scan data is not a big deal for me, but recreating shopping lists is a pain.

## Steps to Reproduce

Install yesterday's update.

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by theoriginalmre** [comment]
The Saved Variables file has been completely destroyed and won't load due to an "overflow" error. I had to delete the lua and lua.bak files from the Saved Variables folder and let the addon create them again for it to work, but I don't know if it will just erase them again later so for now I'm reverting to the previous release. This is where the Shopping Lists were stored :(
