### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by Znuff** [Auctionator/Auctionator#207]
As with any new expansion, the AH is flooded with a lot of items in very small stacks. Basically a lot of auctions.

Today I tried to buy "Leystone Ore". The initial search for prices took over 8 minutes. That's OK.

I was then presented with the prices, then I tried to buy a stack.

http://i.imgur.com/CglLt00.png

Then I was stuck on this window, searching AGAIN, for the last 10 minutes. Eventually the window just disappeared.

**Comment by Znuff** [comment]
Great explanation. Thanks.

**Comment by Vladinator89** [comment]
It would be nice if results were shown live. As the results come in, build a temporary list of auctions, just how it would appear if the scan was done. Add a cancel button, so that the user can stop the scan if they just want to buy the items listed so far. It would solve the issue with servers that have thousands of single unit Leystone Ore posted, and you already scanned 100/5000 of the auctions, and you only need 20 of said item.

**Comment by ceylina** [comment]
This is a known tracked issue. As such this issue was closed as it is a duplicate of work we are trying to accomplish to improve the addon.
