### ISSUE TITLE
Some things not showing up in the "Buy" tab when searching. 

### ISSUE THREAD

**Issue by Oddwin** [Auctionator/Auctionator#232]
When using my shopping list under the buy tab some things are not showing up. Even if they are oh the AH for sure. 

Example: When I search for Ghost Iron Bar the list populates and works as intended.. however.. if I search for Ghost Iron Ore.. it says there is nil on the AH.. I quickly switch to the "browse" tab and there is a TON on the AH. 

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Bug happens with seemingly random items. I just tried searching for Teebu's Blazing long sword.. (there are 3 on my server. But if I search in the buy tab it says there is 0. 

Search for Ghost Iron ore, and Ghost iron bar in the "buy" tab. 

Auctionator, TSM (Tried turning off everything but these 2 addons. still happens. 

No error.

**Comment by moomins** [comment]
This is happening to me too. Notably Defiled Augment Rune. No results under the buy interface but they show up with browse.

One thing to note, I am using the quick search modification.

**Comment by jrob8577** [comment]
@moomins What is the quick search modification?

**Comment by moomins** [comment]
It's the modifications from here:

https://www.reddit.com/r/woweconomy/comments/53j1gd/modifying_auctionator_for_faster_scanning_buying/

It basically removes the pause from scanning and the buy now button which could take several minutes or longer each time if you were trying to search through something that had multiple pages.

And after taking a moment to think about it, it's 100% because it was not usable for my level 100 that the defiled augment runes weren't showing up. I just tried with a level 110 and they show up fine. I don't know if that matters for the ghost iron bars.

**Comment by jrob8577** [comment]
We discussed the implementation of that in Auctionator and decided against it, as it did not make sense as a filter to us.  Does Auctionator work without that modification?

**Comment by moomins** [comment]
Yeah I'm sure all the items would show up fine without the modification, and as I mentioned just realizing you're searching for something that you can't use, that's the reason it isn't showing up because the changes that speed things up make those things not show up since you're toggling the usable flag.
