### ISSUE TITLE
[Search] Shift-Left Click Profession Window

### ISSUE THREAD

**Issue by ManagerWoW** [Auctionator/Auctionator#244]
With 7.1, shift-left clicking an item with a profession window open will cause it to override the auction house search. The AH window should take priority.

http://manager.heroicstrike.org/2016-10-29_02-02-15.mp4

**Comment by ceylina** [comment]
Are you referring to the bug from blizzard that is setting focus on the profession window search box and not the AH? If so that is not something we can readily override and it needs to be fixed on Blizzard's end. Only work around for now is to click the AH button in the profession window to get it to dump mats on a search.

The below image explains what I mean.

![wowscrnshot_103016_104008](https://cloud.githubusercontent.com/assets/9342192/19837707/7478b35a-9e8d-11e6-877e-20efbf3d9c92.jpg)
