### ISSUE TITLE
Broken Scanning

### ISSUE THREAD

**Issue by yesCurtis** [Auctionator/Auctionator#249]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

https://www.reddit.com/r/woweconomy/comments/53j1gd/modifying_auctionator_for_faster_scanning_buying/
This no longer works, and search and buy times are really slow once again, is there a way to fix this and make it work again? Scanning 15 pages used to take like 10 seconds max. Now takes over a minute.

## Steps to Reproduce

Just search under buy section, and wait ages.

## Loaded Addons

Only Auctionator.

**Comment by urgante** [comment]
I tried several combinations of the fix since 7.1 but there are always problems like missing items, not be able to buy or your own auctions not showing. I'm no programmer, only tried to replace some of the code semi-randomly.
I would really appreciate it if you could get the addon to scan as fast as with the fix again.
Also an option to avoid rescan after make an auction on the selling tab would be good.
Thanks for your magnificent addon anyway.
