### ISSUE TITLE
Remove the damn rescan EVERYTIME you sell/buy

### ISSUE THREAD

**Issue by makedir** [Auctionator/Auctionator#333]
The addon is just not usable never was.

- give option to deactivate this
- give option so just limit scans to x pages not ALL
- give option to disable rescan everytime you want to buy something (if the item is gone, so what, there is no need to rescan 3030303 pages everytime and wait 289329 hours)

**Comment by mfutselaar** [comment]
Feel free to fork the project and make changes and do a pull request to implement those changes into the official version of the addon, I'm sure that works faster than coming here with a demanding and rude attitude.

**Comment by squa1o** [comment]
His attitude definitely could be improved, but he has a point. I've been looking at the options for so long trying to find the "deactivate" rescan every time you are going to post an item because I felt like it was something obvious to implement. 

In my opinion its way more comfortable to just scan the whole auction while "afk", and then be able to list all my items very fast with those prices, than being sitting in front of the ah wasting couple minutes on each item if there are many pages. Sadly I have no idea how this things work so I can't do it myself, but would be greatly appreciated if someone could.

**Comment by jrob8577** [comment]
A rescan is necessary in order to ensure the auctions still exist at the originally determined price and stack size. 

👍 to @mfutselaar - I'm happy to take suggestions for improving this experience that will work given the API that Blizzard provides, and especially thrilled when folks submit a PR with said improvements.

Closing this as it duplicates other requests.

**Comment by makedir** [comment]
This is a pure joke right? Read the damn first post and UNDERSTAND it.

IT IS NOT NECCESSARY. How stubborn or blinded are you!? If the auction doesnt exist anymore SO WHAT, give a message "doessnt exist anymore" instead off waiting 20 hours for 2230923 page rescan and in that 20 hour scan the auction is sold away and the 20 hour wait DID NOTHING. Can you even think logical!?

Giving option for a x page scan for example 3 page gives already "good enough data" to approximate a price, you dont need to scan 20309029 pages for that.

**Comment by jrob8577** [comment]
I appreciate your feedback, and will give it the consideration it is due.

**Comment by nullKomplex** [comment]
Attempting to purchase an item that is no longer on the AH doesn't magically nuke the game. Just throw a message that it couldn't be found (like WoW does anyway when Auctionator tries to buy an item that doesn't exist, which happens all the time because of these absurdly long rescans when trying to buy an item, funny that). There's no actual benefit to rescanning every time anyway as it doesn't dynamically update your whole search every scan outside of the single selection you made in the first place.

Just cache the results of the scan, attempt to buy what you're trying to buy, if it fails it fails and move on.

**Comment by jrob8577** [comment]
Thanks @nullKomplex  for the recommendation, this is being tracked in another issue, and has been extensively discussed elsewhere.
