### ISSUE TITLE
Disenchant values in tooltip either unknown or completely wrong

### ISSUE THREAD

**Issue by MrUnlad** [Auctionator/Auctionator#410]
This is constant on every character no matter what addons I have active or deactive, even if Auctionator is the only active one.
Most items disenchant values are always "unknown" and the few times it actually does show a value  it claims the mats I'll recieve are MoP ones, which is obviously not the case when disenchanting BfA items.

**Comment by jrob8577** [comment]
I have not been able to find a table of disenchanting materials, so Auctionator has not been able to provide D/E info since those were last available (I think that was MoP). Any work that will be done to address this, as well as information that can help me update the disenchanting functionality, is being tracked in https://github.com/Auctionator/Auctionator/issues/320. 

In the 8.3 version, disenchanting is currently disabled, and will remain disabled until the D/E materials table can be updated. :(
