### ISSUE TITLE
Auctionator prevent from modifying note, officer note or invite pleople in the guild

### ISSUE THREAD

**Issue by Jobouche** [Auctionator/Auctionator#419]
Please include as much of the following information as possible to help me fix the bug:

There is an error message saying that we cannot modify the note or officer note from guildies as well as inviting pleople in the guild.

The message is specific on Auctionator and ask if you want to deactivate the addon and reload.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

OPEN THE GUILD WINDOWS
CLICK ON A GUILDIE
RIGHT CLICK TO PEN NOTE
TYPE IN THE NOTE
CLICK SAVE - ERROR MESSAGE

![image](https://user-images.githubusercontent.com/58333183/69869882-2c7f3400-127c-11ea-9c57-254e5a676025.png)
![BUG](https://user-images.githubusercontent.com/58333183/69870000-749e5680-127c-11ea-90aa-d04b81f5642a.jpg)

**Comment by jrob8577** [comment]
Please include a big report using an addon like [BugSack](https://www.curseforge.com/wow/addons/bugsack) and re-open. Since Auctionator does not have any interaction with guild frames, I'm guessing that an error is occurring in another addon, and just happens to be caught by some Auctionator error code, but its hard to tell just looking at this.

Thanks!
