### ISSUE TITLE
Can't buy some items in Buy window!!

### ISSUE THREAD

**Issue by M0faZza** [Auctionator/Auctionator#422]
When i wanna buy some sh*t, I can't, because after clicking on item is says scanning instead of buy one.
I try to remove all of addons and try it only with Auct. but nothing worked.
I try to reinstall - nothing.
I try to scann - nothing.
Something is working, something no.
(buying silverleaf yes, buying trinket no.)
For 8.2.0 BfA it's working retardly.

**Comment by jrob8577** [comment]
I'm not sure I understand the issue. Could you please:
1. Provide step by step instructions so that I can replicate this issue.
2. Use an addon like [BugSack](https://www.curseforge.com/wow/addons/bugsack) to see if any errors are being generated, and provide the error message.

Having said this, this probably will not be possible until the 8.3 version is released.
