### ISSUE TITLE
ItemIdFromLink.lua errors (latest discord version)

### ISSUE THREAD

**Issue by Nillx** [Auctionator/Auctionator#440]
Often getting this error:

```
3x ...dOns\Auctionator\Source\Utilities\ItemIdFromLink.lua:2: bad argument #1 to 'find' (string expected, got nil)
[string "=[C]"]: in function `find'
[string "@Auctionator\Source\Utilities\ItemIdFromLink.lua"]:2: in function `ItemIdFromLink'
[string "@Auctionator\Source\Tooltips\Hooks.lua"]:205: in function <Auctionator\Source\Tooltips\Hooks.lua:203>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@FrameXML\ItemRef.lua"]:363: in function <FrameXML\ItemRef.lua:11>
[string "=[C]"]: ?
[string "@Blizzard_CombatLog\Blizzard_CombatLog.lua"]:3520: in function <...aceBlizzard_CombatLog\Blizzard_CombatLog.lua:3461>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetItemRef'
[string "@FrameXML\ChatFrame.lua"]:3735: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>

Locals:
(*temporary) = nil
(*temporary) = "^|c%x+|H(.+)|h%[.*%]"
(*temporary) = "string expected, got nil"

```

**Comment by plusmouse** [comment]
I've hit this bug too, however lack a reproducible test case.

We can obscure the bug by simply testing if itemLink is nil before continuing, but that doesn't explain why we were attempting to tooltip something that wasn't an item in the first place.
```
hooksecurefunc (GameTooltip, "SetQuestLogItem",
  function (tip, type, index)
    local itemLink = GetQuestLogItemLink(type, index)
    local itemId = Auctionator.Utilities.ItemIdFromLink(itemLink)

    local itemCount;
    if type == "choice" then
      _, _, itemCount = GetQuestLogChoiceInfo(index);
    else
      _, _, itemCount = GetQuestLogRewardInfo(index)
    end

    Auctionator.Tooltip.ShowTipWithPricing(tip, itemId, itemCount)
  end
);]
```

**Comment by plusmouse** [comment]
Discovered that it is caused when the tooltip for a world quest as created by the addon "World Quests List" is displayed.
![image](https://user-images.githubusercontent.com/60280559/73208762-eab91f80-413e-11ea-90ff-51762c9d45ed.png)
These tooltips aren't for items, need to update the tooltip code to ignore non-item tooltips.

**Comment by raysmith59** [comment]
I got this error as well, I think it happened when I moused over my mount action button in order to mount (I use Neuron for my action bars so the action buttons are treated as macros, in case that matters).

5x ...dOns\Auctionator\Source\Utilities\ItemIdFromLink.lua:2: bad argument #1 to 'find' (string expected, got nil)
[string "=[C]"]: in function `find'
[string "@Auctionator\Source\Utilities\ItemIdFromLink.lua"]:2: in function `ItemIdFromLink'
[string "@Auctionator\Source\Tooltips\Hooks.lua"]:243: in function <Auctionator\Source\Tooltips\Hooks.lua:241>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@Neuron\Objects\ACTIONBUTTON.lua"]:918: in function `SetSpellTooltip'
[string "@Neuron\Objects\ACTIONBUTTON.lua"]:989: in function `SetTooltip'
[string "@Neuron\Objects\ACTIONBUTTON.lua"]:1022: in function `OnEnter'
[string "@Neuron\Objects\ACTIONBUTTON.lua"]:244: in function <Neuron\Objects\ACTIONBUTTON.lua:244>

Locals:
(*temporary) = nil
(*temporary) = "^|c%x+|H(.+)|h%[.*%]"
(*temporary) = "string expected, got nil"
