### ISSUE TITLE
Still not working as expected 

### ISSUE THREAD

**Issue by Walkerbo** [Auctionator/Auctionator#466]
Please include as much of the following information as possible to help me fix the bug:

## My list of issues
-- Search lists do not run, have to manually run each item within the search list
-- Can only add items by text name, cannot search an item and then add to list
-- No "more" tab, no way to cancel auctions that have been undercut
-- No "buy" tab, no way to buy multiples without having to click buy then confirm

## When issues appear
Not working as expected when opening and using the auction house

## Loaded Addons
-- Auctionator (Auctionator-alpha-0.0.1.zip)
-- Bug grabber
-- Bug sack
I removed my Addons and WTF files to run a true clean test

## Lua error messages
No lua errors 

I may be way beyond the curve with this one as I have not been up on the development process just using twitch to update.

<img width="991" alt="Annotation 2020-02-13 122439" src="https://user-images.githubusercontent.com/35990554/74393064-120d2d80-4e5d-11ea-9adc-7e8f66fc13fa.png">

**Comment by jrob8577** [comment]
This is expected behavior. Please join us in Discord to ask before posting an issue related to functionality - we are working on addressing all of the functional issues, and we are a long way off. In Discord, we can answer pretty quickly what the current behavior is to let you know if it is an unknown bug, or just functionality that has not yet been created.
