### ISSUE TITLE
Create API for other add-ons to use

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#493]
Other addons used Atr_SearchAH(ListName, items) - now broken. This was an unofficial way to search for a list of items

**Comment by vandiel01** [comment]
For ATT, only reason it broke was because of:

Was: if AuctionFrame and AuctionFrame:IsShown() then
Now: if AuctionHouseFrame and AuctionHouseFrame:IsShown() then

But the overall string with:
Atr_SelectPane(3);
Atr_SearchAH(L["TITLE"], missingItems, LE_ITEM_CLASS_ARMOR);
and
Atr_SelectPane(3);
Atr_SetSearchText (name);
Atr_Search_Onclick ();

All just simply broke :)

**Comment by plusmouse** [comment]
The Atr_ stuff is being removed (it's ancient). We could probably put some fake Atr_ functions in to make it look like the API hasn't changed, but, more likely than not, fixing this is going to require changes in the other add-on to work with the new APIs.

**Comment by plusmouse** [comment]
Proposed API:

```lua
Auctionator.API.Initialise()
Auctionator.API.MultiSearch(listOfStrings)
```

With these functions giving an error if called when the ah isn't open, and multiple calls to initialize being undefined behaviour (basically call it wrong, it won't work).

Hopefully this will leave us with enough implementation flexibility to completely redo the internal details without changing the API
