### ISSUE TITLE
Need disenchant stats generation for future xpacs

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#544]

**Comment by Ookami313** [comment]
These are the known DE items that I currently had in my reagent bank sorted into what I believe are the correct expansions. There are some unknowns that I had to guess at because I was using the addon AllTheThings due to it adding a note to the tool tip listing which expansion the item came from. However, some of the items did not show a n expansion in the tool tip, so I guessed based on it's location in my bank to other items around it. Because I try to keep all DE items together based on which expansion they were created in, I'm pretty sure the info is correct. 

The only definite unknowns are the Vanilla/Classic purple shard/crystal from epic gear and the possibility of a Small Prismatic shard in BC. I did not have any in my bank that I could find, so I marked them as as unknown or ?? for verification.

Hope this helps.

-Vanilla
Strange Dust
Illusion Dust
Rich Illusion dust
Lesser Magic Essence (Combine 3 to create a Greater Magic Essence)
Greater Magic Essence
Lesser Eternal Essence (Combine 3 to create a Greater Eternal Essence)
Greater Eternal Essence
Small Brilliant Shard
Large Brilliant Shard
Unknown Purple Shard/Crystal ??

-Burning Crusade
Arcane Dust
Lesser Plannar Essence (Combine 3 to create a Greater Plannar Essence)
Greater Plannar Essence
Small Prismatic Shard ??
Large Prismatic Shard
Void Crystal

-Wrath
Infine Dust
Lesser Cosmic Essence (Combine 3 to create a Greater Cosmic Essence)
Greater Cosmic Essence
Small Dream Shard (Combine 3 to create a Large Dream Shard)
Large Dream Shard
Abyss Crystal

-Cataclysm
Hypnotic Dust
Lesser Celestial Essence (Combine 3 to create a Greater Celestial Essence)
Greater Celestial Essence
Small Heavenly Shard (Combine 3 to create a Heavenly Shard)
Heavenly Shard
Maelstrom Crystal

-Mists
Spirit Dust
Mysterious Essence
Small Ethereal Shard (Combine 3 to create an Ethereal Shard)
Ethereal Shard
Sha Crystal Fragment (Combine 3 to create a Sha Crystal)
Sha Crystal

-Warlords
Draenic Dust
Luminous Shard
Fractured Temporal Crystal (Combine 10 to create a Temporal Crystal)
Temporal Crystal

-Legion
Arkhana
Leylight Shard
Chaos Crystal

-Battle
Gloom Dust
Umber Shard
Veiled Crystal

**Comment by plusmouse** [comment]
Got it 🌞

**Comment by vandiel01** [comment]
Missing:
Classic: Light Illusion Dust

Confirmed:
Lich King: Small Prismatic Shard is confirmed Burning Crusade

Removed:
Classic: Purple Shard is none existence, it was changed to Illusion Dust

**Comment by plusmouse** [comment]
Disenchant stats are OK for now.
