### ISSUE TITLE
Set a maximum amount able to spend while buying from the AH in one session with warning.

### ISSUE THREAD

**Issue by Ookami313** [Auctionator/Auctionator#642]
Ability to set a maximum amount allowed to spend in a session when purchasing from the AH, with a warning stating you're about to spend over the limit set if you go over before finalizing the purchase. 

This will hopefully help prevent people from accidentally overpaying for an item, or items, because they misread what the seller had listed. As an example one seller wanted 10000g per item mixed in with other sellers only wanting 100g and buyer needing all available items accidentally purchases 10 of the 10000g listed items without realizing their mistake before it was to late.

**Comment by plusmouse** [comment]
Doing this feature without hijacking the Blizzard UI would involve creating custom buy screens for Auctionator, this is a significant time investment, without an obvious benefit.

Closing due to age and unlikeliness to implement.

Attached is an addon that blocks purchases of commodities above 5k _unless_ the shift key is held down while clicking both the "Buy" buttons for the purchase. You can change it to a number above 5k by editing the first line of `
[MistakeDodger.zip](https://github.com/Auctionator/Auctionator/files/6933968/MistakeDodger.zip)
MistakeDodger.lua`
