### ISSUE TITLE
Mailbox tool tip improvement for multiple attachments

### ISSUE THREAD

**Issue by jrob8577** [Auctionator/Auctionator#75]
The current tooltip logic for the mailbox is hacked to show the first element's auctionator info on the tooltip when hovering over an item with multiple attachments.  Need to include logic to aggregate info and show the sum.

```lua
hooksecurefunc (GameTooltip, "SetInboxItem",
  function (tip, index, attachIndex)
    -- TODO
    local attachmentIndex = attachIndex or 1
    local _, _, _, num = GetInboxItem(index, attachmentIndex);
    Atr_ShowTipWithPricing (tip, GetInboxItemLink(index, attachmentIndex), num);
  end
);
```

**Comment by jrob8577** [comment]
Probably need this function [http://wowprogramming.com/docs/api/GetInboxHeaderInfo](http://wowprogramming.com/docs/api/GetInboxHeaderInfo) if we can map to item being hovered (I'm guessing that's the `index` param)

**Comment by ceylina** [comment]
Should still be able to do it with some of the changes to GetInboxItem

local name, itemID, itemTexture, count, quality, canUse = GetInboxItem(Index, itemIndex);

the constant for an necessary loop's to limit is ATTACHMENTS_MAX_RECEIVE 

GetInboxHeaderInfo and itemCount would only be the return needed to validate the attachments (if any) count.

So something along the lines of (dry coded ripping off my favorite mail addon)


hooksecurefunc (GameTooltip, "SetInboxItem",
  function (tip, index, attachIndex)
    for i = 1, ATTACHMENTS_MAX_RECEIVE do
    local name, _, _, num = GetInboxItem(index, i);
    if name then
        local itemLink = GetInboxItemLink(index, i) or name
	  	if num > 1 then
			Atr_ShowTipWithPricing (tip, itemLink, num);
		else
			Atr_ShowTipWithPricing (tip, itemLink);
		end
    end
  end
);

**Comment by ceylina** [comment]
You may also have to hook the global InboxFrameItem_OnEnter and not GameTooltip.SetInboxItem or in addition to in order to get the tooltip on the multiple attachments

https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/MailFrame.lua


in other words... might not be worth the hassle. People can always open multiple attachment boxes to peek inside ;)

**Comment by Veyska** [comment]
Option to disable this?  It's a nice feature and everything, but my mailbox tooltips are getting rather cluttered because that makes two different addons doing the same thing and the other one's specifically oriented around mailbox stuff.  :-P  (It's easy enough to manually disable, but an in-game disable would be nicer if possible.)  Thanks!
