### ISSUE TITLE
Support posting Auctions in the Selling Tab

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#820]
Is your feature request related to a problem? Please describe.
There doesn't seem to be a way to actually start an auction through the new Selling tab. It appears to only assume that everything is posted in Buyout mode.

Describe the solution you'd like
I'd like a way to put up items up for auction through the selling tab. That is to say, actual auctions rather than things in buyout mode. 

Describe alternatives you've considered
I can switch to the normal Auction tab but it doesn't seem to have all the historical data that Auctionator keeps from the scan. For example, I just put up for auction a Darkmoon Eye. In the "Selling" tab, auctionator correctly showed that there were previous auctions at high price for the item - I think it was over 100K. But, when I switched to the "Auction" tab, it showed as a default price only 95gold which is nowhere near accurate. Undermine Journal was reporting an average of somewhere around 120K gold in my realm.

Note: I'm going to keep on opening this issue.  THIS IS BASIC FUNCTIONALITY.  This is what something called "AUCTIONator" is and should be all about- posting auctions!!  For me, at least, there is no value to using Auctionator without this feature.  The only thing it does, that other add-ons don't do, is to set default duration.  I can do that manually.
Please reconsider your position - this is something Auctionator used to be able to do...

**Comment by jrob8577** [comment]
@sauljaffe Author here. First, I appreciate your insistence on functionality you *want*, but if it is something we decide not to implement, argumentative opening of tickets will not support your cause. 

Having said that, I'd like to challenge you to design (both the UI and the workflow for) the thing you want and present it, with the constraint that we will not add functionality to an existing Blizzard tab - this ends up causing major throttling issues that we have not been able to get around, and has repercussions on all of the Auctionator functionality. 

I look forward to seeing what you come up with!

**Comment by sauljaffe** [comment]
I'm sorry but I'm not conversant in LUA and so that's kind of a straw argument/challenge.  If I were conversant, I'd just write my own add-on.  I've been a computer programmer for many years...

As for "argumentative opening of tickets", well, here is another argument: Auctionator USED to do this.  Why is it considered beyond the realm of possibility/likelihood to do this now?  What has changed?  I'll admit that Blizzard has changed the Auction house but it's basic functionality remains unchanged.  Auctionator is, and always was, supposed to be an add-on to help people place AUCTIONS.  Why is that now outside the the area of what Auctionator is doing, or going to do?  And, I would argue further, that if placing AUCTIONS is something you are not going to implement, then you should change the name of the add-on to something like Sellinator because you're no longer involved in auctions.

FYI: "argumentative opening of tickets" only appears to be necessary (at least to me) when someone just goes and closes tickets so that further comments cannot be made.  In every job I've ever had, and every volunteer project I've ever been involved in, tickets weren't just summarily closed until they were actually resolved.  And simply saying: "I don't think we should implement this" is not a resolution without giving people the opportunity to show support one way or the other.  Other sites, or authors, for example, will leave things open for some period of time like 30 days to see how much support there is for an idea before decided whether or not to implement it and/or close the ticket.

**Comment by jrob8577** [comment]
@sauljaffe I'm not asking for implementation, I'm asking for a representation of the UI (images or wireframes would be great) and a description of how you would want the UI to work. As an aside, I was not conversant in LUA prior to picking up this add-on, but as a programmer of many years, I'm sure you can agree that new languages are straightforward to pick up.

I apologize if sufficient reasoning was not provided in the ticket prior to closing, but the closing of an issue does not prevent you from from continuing to state your case in that issue (or even re-opening the issue, if I remember correctly; I'm not sure if my permissions are somehow different from yours on the issue board, though I do not recall ever explicitly setting anything up related to issue permissions). Another option would be to visit the Discord server, where we have many active users who could weigh in on this feature request, and help make the case for or against.

All this being said, I'll restate my earlier point: if we decide not to implement something, whether because we do not think it fits the vision we have for the set of functionality we provide in Auctionator, or because we estimate that the cost of implementation is too high given the expected reward obtained from the feature, then we will not implement it. We may add the feature request to our internal backlog, but unless a feature is on the backlog scheduled for eventual implementation, we do not keep tickets open indefinitely, in an effort to keep our issue board clean.

In the event that none of these options are to your liking, I am happy to provide you with a gsub you can use to replace all instances of the string `Auctionator` with `Sellinator`, though the semantic distinction in my mind is lacking (if you're selling via the creation of auctions on the auction house, are you not auctioning?). I can take the permanent name change under advisement, but `Sellinator` does not have quite the same cachet to my ear as `Auctionator`.

**Comment by sauljaffe** [comment]
@jrob8577 My apologies for not responding sooner.  I lost power in the storm and I'm just now playing catch-up with everything.

I'm going to try and address all your points.  Forgive me if I miss one or two.

First, as to a representation of the UI - someone posted a graphical representation on the other thread that, as I said, seemed sufficient.  

An "auction" is defined as putting something up for sale **to the highest bidder**.  If you're not putting something up for bid, therefore, you are not posting an auction, you're just posting a "sale".

I'm not sure why this is an issue.  Auctionator used to be able to do this in previous versions.  The mechanisms and code was probably there already before you did a re-write.  It seems to me that it should be a non-issue - there should be a way to put things up for bid in a program called "Auctionator" that describes itself as:  "Auctionator is designed for casual everyday auction house users. Auctionator makes the auction house easier to use, by presenting auction house listings clearly and succinctly, and by eliminating the tedium involved in posting and managing auctions."  Note that the word used is "auctions" which means putting things up for "bidding" because that's in the very basic definition of "auction" - selling to the highest "bidder".

In any event, as I see it, the functionality, rather than the UI is what is important.  You can make it look however you want, but the functionality should be pretty much the same as what is available on the "Sell" page with the added bonus (if possible) of presetting the buyout price to whatever you would set it to if you weren't placing an auction as it does now in the "Selling" tab.  That is to say, the basic functionality is:
    - able to specify an auction, rather than a buyout
    - the ability to set a buyout price for the auctioned item (preset to the amount taken from the historical scanned data, or other already existing auctions, and offset by whatever undercutting value is specified.)
    - the ability to set a minimum bid price
    - the ability to set the duration of the auction
    - the ability to set the quantity (if you have more than 1 of the item)
    - to see the deposit amount necessary to place the bid
    - the ability to start (create) the auction
As I said, all of this is on the "Sell" tab with the exception of the presetting of the buyout price.
   
And that's another thing: I fail to understand why a separate tab is needed.  It worked quite fine as one tab in earlier versions and, as I said in the other thread, if you're not adding functionality to the process why have a separate tab?  I understand that you have said that you were making the separate tab in order to get around a race condition but there are many ways of getting around race conditions, as any programmer knows.  I'm not going to go into them here because the ways of getting around race conditions vary depending on the actual race condition.  It's easy to do a google search and find ways around most types of race conditions.  I'm about 99% certain that you are not the only authors of an add-on for WoW that has faced a race condition problem and other authors have probably found reasonable ways around the same problem without having to design a whole separate UI...

As for re-opening an issue or continue to post on a closed issue: us peons without the priveleges you have, cannot do so.  I know of no way to post to a "closed" issue.  In order to re-open it, we have to start a new thread which is, essentially, what I did.  BTW, I don't use Discord.  I have it, I just don't use it.  Many reasons... 

But, the bottom line here is that what you are providing is NOT a tool that "eliminates the tedium involved in posting and managing auctions" but rather a tool that "eliminates the tedium involved in posting things for sale on the auction house".  There is a difference.
