### ISSUE TITLE
"My auctions" tab

### ISSUE THREAD

**Issue by Ixorai** [Auctionator/Auctionator#840]
Before the last patch I was working a lot with the prices of my last auctions, would it be possible to add that tab or something similar?

**Comment by plusmouse** [comment]
Is this to view while posting auctions?

**Comment by MarshallBuhl** [comment]
I'm not sure what you mean by this, so my apologies in advance if my comment is inappropriate.  

When reauctioning an item I would like to see my last auction price.  I'm assuming it failed because I was asking too much.  Maybe this isn't possible with WoW.  

Rift had a far superior auction house.  Instead of mailing your failed auctions, they remained in the AH and you could either reauction them or claim them.  I suppose that made it easy to show what your last asking price was.  It also showed a graph of price history.  Nice stuff.

**Comment by plusmouse** [comment]
Find this in alpha 433
