### ISSUE TITLE
Realm Price History Issue

### ISSUE THREAD

**Issue by c1v1d** [Auctionator/Auctionator#957]
Hello,

The Realm Price History isn't always accurate (photo attached). The problem occurs when someone lists an item for 1 Gold for example. Aucionator will default the Realm Price History to the lowest listing of the day, i.e. 1 Gold. I believe a simple solution would be to show the average price of all listings for the day instead of just the lowest. Please let me know if I am missing something, or doing something wrong as this is only my first few days using the addon. 

Thanks!

![AH](https://user-images.githubusercontent.com/76636269/103162609-4c06ca00-47b8-11eb-90ad-e884862ef0d3.jpg)

**Comment by plusmouse** [comment]
Not exactly a fix, but you can show an extra column which shows the highest lowest price for the day, right-click on the column header and choose "Upper Unit Price":
![image](https://user-images.githubusercontent.com/60280559/103164625-a712de00-4805-11eb-892e-77c80807fb68.png)

**Comment by MyDevil94** [comment]
I like the "lowest Price". If you are quick enough, you can buy it and sell it again.
For the "History" it is bad. Thats right.
Maybe an option "new lowest price < old lowest price - 90% -> Fake". Then write it in an extra column of the day. Because who knows.. maybe the fake price is the reason for lower prices tomorow.
(A place in settings for the percentage would be nice. Everyone can set it by himself)

But then it has to open a window with all the "fake" prices after AH Scan. Then you can choose.. buy or not 👍

**Comment by plusmouse** [comment]
Auctionator isn't going to include any estimates of prices, or formulas to calculate a price that seems right. Read [this document](https://github.com/Auctionator/Auctionator/wiki/In-item-tooltips,-why-does-Auctionator-display-the-most-recently-scanned-price-rather-than-an-average-of-some-sort), for an explanation why.
