### ISSUE TITLE
Open Blizzard's bags instead of bag addon's

### ISSUE THREAD

**Issue by class2u** [Auctionator/Auctionator#97]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I'm using [DJBags addon](http://mods.curse.com/addons/wow/djbags) in Legion beta. When Auctionator opens bags automatically, it opens Blizzard's bags instead of bag addon's.

## Steps to Reproduce

1.  Open auction.
2.  Click the tabs of Auctionator (buy, sell and other) in auction.

## Loaded Addons

- !BugGrabber
- BugSack
- Auctionator
- DJBags

## Back Trace (LUA Error Output)

None.

**Comment by ceylina** [comment]
Due to the overwhelming differences in bag addons, it is nearly impossible to code against the many ways to open bags. We will remove/disable the default option within Auctionator to open bags when opening the auction house. This will mean that you will need to enter "b" or "shift-b" to open your bags as DJBags has no code at the moment to open bags when entering the auction house. Please feel free to open a ticket with the addon author of that addon if you feel they should have that functionality as Auctionator will no longer attempt to open bags

**Comment by class2u** [comment]
Thanks for this info. :)
